プラクティス：Rails の i18n を理解する
chihaso/Rails_textbook_books_app pull request #1
Opened 2019-09-24 07:26 UTC by chihaso

Railsの教科書で作ったアプリを、英語と日本語対応に修正しました。
### 変更点
* TLDからのロケール取得機能を追加
* インデックスページに言語切り替え用のリンクを追加
* 翻訳ファイルの追加
* ページタイトル、データ項目名、リンクの表示を国際化

2019-09-26 05:24 UTC, komagata requested changes

2019-09-26 05:24 UTC, komagata commented on app/views/books/edit.html.erb
> +<h1><%= I18n.t 'books_app.page_title.edit' %></h1>
viewのコンテクストでは`t`だけで呼び出せますー

2019-09-26 05:24 UTC, komagata commented on app/views/books/index.html.erb
> +<% p I18n.locale %>
これは不要っぽいです。

2019-09-26 07:47 UTC, chihaso commented on app/views/books/edit.html.erb
> +<h1><%= I18n.t 'books_app.page_title.edit' %></h1>
ご指摘ありがとうございます！
viewファイルの中の`I18n.t`を`t`に修正しました。

2019-09-26 07:54 UTC, chihaso commented on app/views/books/index.html.erb
> +<% p I18n.locale %>
ご指摘ありがとうございます！
デバッグ用のものを消し忘れていました；失礼いたしました。
削除いたしました！

2019-10-01 13:22 UTC, closed without merging

2019-10-02 05:04 UTC, chihaso commented
リポジトリのコミットメッセージに日本語と英語が混在している問題を修正するため、本PRをクローズします。
修正後、改めてPRを発行します。