プラクティス:コメントを付けられるようにする
chihaso/Rails_textbook_books_app pull request #10
Opened 2019-11-15 08:55 UTC by chihaso

Railsの教科書で作ったアプリに、コメント機能を実装しました。

### masterからの変更点
* 日報の追加
* コメント機能の追加
* 本人以外の日報・コメントの削除・編集の禁止

ご確認のほど、宜しくお願いいたします。

2019-11-15 10:00 UTC, komagata commented on test/models/report_test.rb
> +# frozen_string_literal: true
使ってないファイルは削除でお願いします〜

2019-11-15 10:51 UTC, chihaso commented on test/models/report_test.rb
> +# frozen_string_literal: true
失礼いたしました！🙇‍♂️
使っていないテストファイルを削除いたしました。

2019-11-16 02:21 UTC, komagata requested changes

2019-11-16 02:21 UTC, komagata commented on app/controllers/books_controller.rb
> +    @book.user = User.find current_user.id
```suggestion
    @book.user = current_user
```

2019-11-18 03:20 UTC, chihaso commented on app/controllers/books_controller.rb
> +    @book.user = User.find current_user.id
ありがとうございます！
コミットいたしました。

2019-11-18 04:55 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2019-11-18 05:03 UTC, merged