プラクティス:kaminari を使ってページング処理を実装する (再)
chihaso/Rails_textbook_books_app pull request #4
Opened 2019-10-02 07:10 UTC by chihaso

コミットメッセージの修正に付随して[前回PR]()がクローズされたので、再発行いたします。

Railsの教科書で作ったアプリに、kaminariによるページング処理を実装しました。

### masterからの変更点
* kaminariのインストール
* indexページにページング処理を実装
* 翻訳ファイルにページング用の翻訳データを追加
* 一部`I18n.t`が残っていたので`t`に変更

2019-10-02 14:55 UTC, komagata commented
i18nがmasterにマージされたらこちらのブランチにそちらを取り込んでいただければー

2019-10-03 01:42 UTC, chihaso commented
@komagata コメントいただきありがとうございます！
i18nをマージしたmasterを取り込みました。
ご確認のほど、よろしくお願いいたします。

2019-10-04 03:23 UTC, komagata requested changes

2019-10-04 03:23 UTC, komagata commented on app/controllers/books_controller.rb
>      respond_to do |format|
すみません、これは以前のときにいうべきだったんですが、JSONのAPIとして使うことがなければこのあたりの処理は削除したほうがいいと思いますー

2019-10-04 04:44 UTC, chihaso commented on app/controllers/books_controller.rb
>      respond_to do |format|
ご指摘ありがとうございます！
JSON形式をリクエストされた場合の処理を削除いたしました。
ご確認をお願いいたします。

2019-10-04 06:36 UTC, komagata requested changes

2019-10-04 06:36 UTC, komagata commented on app/controllers/books_controller.rb
> +        format.html { redirect_to @book, notice: t("books_app.notice.success.create") }
1種類しか対応するフォーマットがない場合はformat自体必要ないです。
このrespond_toが何やっているのかを調べるとよくわかるかもですー。

2019-10-04 07:02 UTC, chihaso commented on app/controllers/books_controller.rb
> +        format.html { redirect_to @book, notice: t("books_app.notice.success.create") }
ご指摘ありがとうございます！
respond_toメソッド自体不要と思われましたので、削除いたしました。
再度ご確認をお願いいたします。

2019-10-04 07:05 UTC, komagata requested changes

2019-10-04 07:05 UTC, komagata commented on app/controllers/books_controller.rb
> +      format.html { render :edit }
このformatは動かないかもです。

2019-10-04 07:16 UTC, chihaso commented on app/controllers/books_controller.rb
> +      format.html { render :edit }
確認不足でした。すみません！
formatを削除いたしました。

2019-10-04 08:36 UTC, komagata requested changes

2019-10-04 08:36 UTC, komagata commented on app/controllers/books_controller.rb
> +      frender :new
```suggestion
      render :new
```

2019-10-04 10:17 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2019-10-04 22:24 UTC, merged