プラクティス:deviseを使ってユーザー認証を実装する
chihaso/Rails_textbook_books_app pull request #5
Opened 2019-10-08 03:15 UTC by chihaso

Railsの教科書で作ったアプリに、kaminariによるページング処理を実装しました。

### masterからの変更点
* deviseのインストール
* Userモデルの追加
* ユーザー情報として郵便番号、住所、自己紹介文を追加
* ユーザープロフィールページを追加

2019-10-08 05:21 UTC, komagata requested changes

2019-10-08 05:21 UTC, komagata commented on app/assets/stylesheets/users.scss
> +// Place all the styles related to the Users controller here.
このファイルは使わなければ削除しちゃった方が良さそうですー

2019-10-08 05:21 UTC, komagata commented on app/helpers/users_helper.rb
> +module UsersHelper
このファイルも実装がなければ削除した方が良さそうです。

2019-10-08 05:21 UTC, komagata commented on config/locales/devise.views.en.yml
> +en:
[devise を使ってユーザー認証を実装する \| FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/practices/40)

ここのよくあるミスを参照してみてください〜

2019-10-08 05:21 UTC, komagata commented on test/fixtures/users.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
これもいらないっぽいです

2019-10-08 05:21 UTC, komagata commented on test/models/user_test.rb
> +require 'test_helper'
テストも実装がない場合削除してください〜

2019-10-08 06:46 UTC, chihaso commented on app/assets/stylesheets/users.scss
> +// Place all the styles related to the Users controller here.
ご指摘ありがとうございます！
books.scssと併せて削除いたしました。

2019-10-08 06:47 UTC, chihaso commented on app/helpers/users_helper.rb
> +module UsersHelper
ご指摘ありがとうございます！
削除いたしました。

2019-10-08 06:48 UTC, chihaso commented on test/fixtures/users.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
ご指摘ありがとうございます！
削除いたしました。

2019-10-08 06:48 UTC, chihaso commented on test/models/user_test.rb
> +require 'test_helper'
ご指摘ありがとうございます！
削除いたしました。

2019-10-10 06:38 UTC, chihaso commented on config/locales/devise.views.en.yml
> +en:
ご指摘ありがとうございます！
devise-i18nの翻訳ファイルを削除し、必要な翻訳文を自前の翻訳ファイルに書き足す形で統合しました。

2019-10-10 07:37 UTC, komagata requested changes

2019-10-10 07:37 UTC, komagata commented on app/views/layouts/application.html.erb
> +    <%= link_to_if request.host.split('.').first != 'ja', '日本語',   "http://ja.localhost:3000#{request.path}"%> |
ちょっとした処理が必要になる場合は、ControllerかViewHelperに書いたほうがいいですー。

また、この書き方ですとdevelopment環境でしか動かないことになってしまうのでそこに依存しない書き方を考えてみてください。

2019-10-10 07:37 UTC, komagata commented on test/controllers/users_controller_test.rb
> +
不要な空行があるようです。

2019-10-16 04:02 UTC, chihaso commented on test/controllers/users_controller_test.rb
> +
ご指摘ありがとうございます！
空行を削除しました。

2019-10-16 08:15 UTC, chihaso commented on app/views/layouts/application.html.erb
> +    <%= link_to_if request.host.split('.').first != 'ja', '日本語',   "http://ja.localhost:3000#{request.path}"%> |
ご指摘ありがとうございます！
* ロケールの設定方法をクエリを使用する方法に変更し、環境依存の記述を排除しました。
* リンク生成コードをViewHelperに移動しました。

2019-10-16 08:30 UTC, komagata commented on app/helpers/application_helper.rb
> +      link_to_if params[:locale] != "ja", "日本語",   "#{request.domain.split("/")[2]}#{request.path}?locale=ja"
link先のURLって`/foo`とかPATHだけでも大丈夫だと思いますー

2019-10-16 08:46 UTC, chihaso commented on app/helpers/application_helper.rb
> +      link_to_if params[:locale] != "ja", "日本語",   "#{request.domain.split("/")[2]}#{request.path}?locale=ja"
ご指摘ありがとうございます！
ほんとだ・・・！

PATHだけの記述に修正しました。

2019-10-16 23:49 UTC, komagata commented on app/helpers/application_helper.rb
> +      exit
exitは危険な気がします。その後の処理が全部終了しちゃいそう。

メソッドの引数にデフォルト値を設定しておくとかでいいと思います。

2019-10-16 23:49 UTC, komagata commented on test/controllers/users_controller_test.rb
> +require 'test_helper'
この辺り、rubocop通してるとシングルクォーとが引っかかる気がしますー

2019-10-18 08:21 UTC, chihaso commented on app/helpers/application_helper.rb
> +      exit
ご指摘ありがとうございます！
おっしゃる通り処理が終了してエラーになってしまいました；

非対応の言語コードが渡された場合はエラーメッセージを表示するよう修正いたしました。

2019-10-18 10:09 UTC, chihaso commented on test/controllers/users_controller_test.rb
> +require 'test_helper'
コード規約の確認を怠っていました。すみません・・・。

`rubocop --auto-correct` で修正し、offenseが検出されなくなることを確認いたしました。

2019-10-21 02:07 UTC, komagata requested changes

2019-10-21 02:07 UTC, komagata commented on app/helpers/books_helper.rb
> +# frozen_string_literal: true
実装が無いクラス・モジュールは削除しちゃってください〜

2019-10-21 12:09 UTC, chihaso commented on app/helpers/books_helper.rb
> +# frozen_string_literal: true
ご指摘ありがとうございます！
プロジェクトフォルダ内を一通り確認し、現時点で使用していないファイルを削除しました。
ただ、`config/initializers`下のファイルと`.keep`ファイルについては、コメントのみだったり空であっても、ファイルが存在すること自体に意味があるように思いましたので、そのまま残しております。

ご確認のほど、よろしくお願いいたします。

2019-10-21 14:53 UTC, komagata commented on app/views/books/index.json.jbuilder
> +# frozen_string_literal: true
この辺り、JSONでアクセスする必要が無い場合は削除しちゃってください〜

2019-10-22 03:09 UTC, chihaso commented on app/views/books/index.json.jbuilder
> +# frozen_string_literal: true
ご指摘ありがとうございます！
JSONは使っていないので、.jbuilderは削除いたしました。

2019-10-22 08:17 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2019-10-22 13:55 UTC, merged