プラクティス:omniauth を使って GitHub 認証を実装する
chihaso/Rails_textbook_books_app pull request #6
Opened 2019-10-24 06:46 UTC by chihaso

Railsの教科書で作ったアプリに、OmniAuthでGitHubアカウントによる認証機能を実装しました。

### masterからの変更点
* OmniAuthのインストール
* omniauth-githubのインストール
* 認証情報に対応するユーザーの検出処理追加
* コールバック処理とルーティング追加

ご確認のほど、宜しくお願いいたします。

2019-10-25 06:24 UTC, komagata commented on config/initializers/devise.rb
> +  config.omniauth :github, "391c5ba7048517e938f1", "2996363313f4dbb6e33e1779103b1ded54115b52"
これがソースコード管理に含まれてるとまずいので、わからないようにする仕組みを調べてみてください。
また、この内容が入ってる履歴自体を削除しちゃってください。

環境変数から読み込む方法やCredentionsを使う方法があります。

2019-10-28 08:00 UTC, komagata requested changes

2019-10-28 08:00 UTC, komagata commented on Gemfile
> +gem "dotenv-rails", groups: [:development, :test]
このgroupはすでにあるのでそこに書くのがいいと思います。

2019-10-29 03:03 UTC, chihaso commented on Gemfile
> +gem "dotenv-rails", groups: [:development, :test]
ご指摘ありがとうございます！
わからないままにREADME通りに書いてしまっていました…すみません。
dotenv-railsの記述を既存のgroup内に移動しました。。

2019-10-30 08:18 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2019-10-30 08:59 UTC, merged