プラクティス:Railsでユーザーフォローを作る
chihaso/Rails_textbook_books_app pull request #8
Opened 2019-11-07 05:52 UTC by chihaso

Railsの教科書で作ったアプリに、ユーザーフォロー機能を実装しました。

### masterからの変更点
* ユーザー間のフォロー関係を保持するfollowsテーブルの追加
* フォロー/アンフォローボタンの追加（Ajaxでページ遷移なしで動作するように）
* フォロー一覧、フォロワー一覧ページの追加

ご確認のほど、宜しくお願いいたします。

2019-11-09 00:13 UTC, komagata requested changes

2019-11-09 00:13 UTC, komagata commented on db/migrate/20191108135120_change_post_user_id_to_books.rb
> +    change_column_default :books, :post_user_id, nil
これはシンプルに`user_id`でいいと思います。

2019-11-09 00:13 UTC, komagata commented on app/views/follows/create.js.erb
> +target.innerHTML = '<%= escape_javascript(render("users/unfollow", user: @user)) %>';
最終行に改行が無いようです。

2019-11-09 00:14 UTC, komagata commented on app/views/follows/create.js.erb
> +target.innerHTML = '<%= escape_javascript(render("users/unfollow", user: @user)) %>';
エディターで自動的に最終行に改行が入る設定にしたほうがいいかもです。VSCodeにもそういう設定あったとおもいます。

2019-11-11 14:11 UTC, chihaso commented on app/views/follows/create.js.erb
> +target.innerHTML = '<%= escape_javascript(render("users/unfollow", user: @user)) %>';
ご指摘ありがとうございます！
最終改行のなかったerbファイルに改行を追加しました。
VSCodeの設定も自動で改行を入れるように変更いたしました。

2019-11-11 14:50 UTC, chihaso commented on db/migrate/20191108135120_change_post_user_id_to_books.rb
> +    change_column_default :books, :post_user_id, nil
ご指摘ありがとうございます！
user_idに改名いたしました。

2019-11-13 03:04 UTC, komagata requested changes

2019-11-13 03:04 UTC, komagata commented on app/controllers/users_controller.rb
> +  def following
プラクティスの参考のところのURLの内容のように、Controllerを分けるといいと思います〜

2019-11-13 03:04 UTC, komagata commented on app/models/follow.rb
> +  validates :follower_id, presence: true
belongs_toをしている時点でデフォルトで必須になっているので`_id`の方にvalidationはいらないと思います〜

2019-11-14 04:14 UTC, chihaso commented on app/models/follow.rb
> +  validates :follower_id, presence: true
ご指摘ありがとうございます！
そうでした・・・！
validationを削除いたしました。

2019-11-14 06:17 UTC, chihaso commented on app/controllers/users_controller.rb
> +  def following
ご指摘ありがとうございます！
なるほど、こういう時に分割するといいんですね…
CRUD以外のアクションを別コントローラに切り出しました。

2019-11-14 10:55 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2019-11-14 12:22 UTC, merged